### ISSUE TITLE
MusicManager does not handle connection failures

### ISSUE THREAD

**Issue by Nytelife26** [syrus-bot/syrus-bot#34]
**Describe the bug**
Upon the MusicManager failing to connect to Lavalink, it spews an endless stream of errors until the bot connects successfully.

**Reproducible By**
1. Launch Syrus without Lavalink, or parallel to Lavalink initialization
2. Observe console logs
  * Connection fails
  * Error reported

**Expected behavior**
A handler so the bot catches the error and keeps trying without crashing and restarting the entire bot.

**Logs / Screenshots**
```js
syrus_1     | events.js:292
syrus_1     |       throw er; // Unhandled 'error' event
syrus_1     |       ^
syrus_1     | 
syrus_1     | Error: connect ECONNREFUSED 172.25.0.2:2333
syrus_1     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
syrus_1     | Emitted 'error' event on MusicManager instance at:
syrus_1     |     at WebSocket.error (/opt/Syrus/node_modules/lavalink/dist/src/core/Connection.js:39:27)
syrus_1     |     at WebSocket.emit (events.js:315:20)
syrus_1     |     at ClientRequest.<anonymous> (/opt/Syrus/node_modules/lavalink/node_modules/ws/lib/websocket.js:568:15)
syrus_1     |     at ClientRequest.emit (events.js:315:20)
syrus_1     |     at Socket.socketErrorListener (_http_client.js:469:9)
syrus_1     |     at Socket.emit (events.js:315:20)
syrus_1     |     at emitErrorNT (internal/streams/destroy.js:106:8)
syrus_1     |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
syrus_1     |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
syrus_1     |   errno: -111,
syrus_1     |   code: 'ECONNREFUSED',
syrus_1     |   syscall: 'connect',
syrus_1     |   address: '172.25.0.2',
syrus_1     |   port: 2333
syrus_1     | }
```

**Desktop (please complete the following information):**
- Docker 19.03.6
- Ubuntu 18.04 LTS Server
- Using `syrus/bot` docker image for node (14.15.1, in Alpine Linux 3.10)

**Additional context**
N/A.

**Comment by Nytelife26** [comment]
Fixed in 664e501
